# Generated by Django 2.1.1 on 2018-11-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mute',
            field=models.BooleanField(default=False),
        ),
    ]
