# Generated by Django 2.0 on 2018-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_user_mute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mute',
            new_name='mute_email',
        ),
        migrations.AddField(
            model_name='user',
            name='mute_inbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mute_txt',
            field=models.BooleanField(default=False),
        ),
    ]
